sample:
	g++ -o cor testcoroutine.cpp -I/home/zhangjun-s/opt/boost/include/boost-1_53 -L/home/zhangjun-s/opt/boost/lib -Wl,-R/home/zhangjun-s/opt/boost/lib -lboost_context-gcc41-d-1_53

gentor:
	g++ -o gentor gentor.cpp -I/home/zhangjun-s/opt/boost/include/boost-1_53 -L/home/zhangjun-s/opt/boost/lib -Wl,-R/home/zhangjun-s/opt/boost/lib -lboost_context-gcc41-d-1_53
